### PR TITLE
Update LEDExample.ino: Use LED_PIN Constant

### PR DESCRIPTION
**Pull request by WSorban**
Since you are defining the LED pin, you should use it. And since it's a constant, you should define it as such. Also, pin 13 is usually the default LED pin on most Arduinos.

### CODE REVIEW

**Comment by HirdayGupta** [comment]
@WSorban Due to the merge of #1, this PR now has a merge conflict. Requesting you to correct the conflict before we go ahead with this merge.

Also, regarding the changes, I completely agree that if LED Pin has been defined, then it should be used. My apologies for not having done this already, I was a little young when I wrote this 😅 

And yes, Pin 13 is definitely better as it is indeed the default on most arduinos. 

I just have one question: Why is `#define LED_PIN (int8_t)13` better than a simple `int LED_PIN = 13`?

**Comment by WSorban** [comment]
@HirdayGupta Hi there, sorry for the late reply. Generally speaking, it's good programming practice to set something as final/constant, when you know you will no longer change that value. It's good for more than one reason. For instance, if you define something as constant, and later, attempt to change the value, you will get a compile time error. But if you set it up as variable, you will not get that, and you may encounter bugs in your code, and waste time finding them. Apart from that, it also helps with readability, as when somebody that reads your code, you want to let them know that something won't change anywhere in the code.

**Comment by HirdayGupta** [comment]
Thanks for your contribution @WSorban (And sorry for the delay in merging this in)!!

**Comment by HirdayGupta** [comment]
Also, @WSorban, I'm curious, did you use this library in a project? If so, how useful was it? Any improvements/feature additions you would suggest making?

**Pull request merged**
